-- 创建数据库 REHome
CREATE DATABASE IF NOT EXISTS REHome
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

-- 创建数据库管理员账号 REHomeAdmin
CREATE USER IF NOT EXISTS 'REHomeAdmin'@'%' IDENTIFIED BY 'REHomeAdmin2024!';
GRANT ALL PRIVILEGES ON REHome.* TO 'REHomeAdmin'@'%' WITH GRANT OPTION;

-- 刷新权限
FLUSH PRIVILEGES;
